/**
 * The SingleTrack warehouse catalogue.
 *
 * Generated from the consolidated inventory spreadsheet by
 * scripts/import-inventory.py — re-run that rather than editing this file, so
 * the warehouse list and the app cannot drift apart.
 *
 * `hold` is the largest quantity any single event needs: the minimum the
 * warehouse must carry to run that event without hiring in. It becomes the
 * item's low-stock level. Quantities on hand are deliberately absent — the
 * spreadsheet records what the packing lists say, not a physical count.
 */

export interface CatalogueItem {
  name: string;
  sku: string;
  unit: string;
  /** Largest single-event requirement, used as the reorder threshold. */
  hold: number;
  consumable: boolean;
  note: string;
  /** Event code to the quantity that event packs, across all its sites. */
  needs: Record<string, number>;
}

export interface CatalogueGroup {
  category: string;
  icon: string;
  items: CatalogueItem[];
}

export const EVENT_LISTS: Array<{ code: string; name: string; year: number }> = [
  { code: 'KT', name: 'Kilcunda Trail Running Festival', year: 2026 },
  { code: 'BB', name: 'Snow Gum Run / Razorback Run', year: 2026 },
  { code: 'BSF', name: 'Buffalo Stampede', year: 2026 },
  { code: 'AC', name: 'Alpine Challenge', year: 2026 },
  { code: 'WP', name: 'Wilsons Prom', year: 2026 },
  { code: 'WR', name: 'Wonderland Run', year: 2026 },
  { code: 'HC', name: 'Hounslow Classic', year: 2025 },
  { code: 'PBRF', name: 'Puffing Billy Running Festival', year: 2025 },
  { code: 'RCR', name: 'Roller Coaster Run', year: 2025 },
  { code: 'GPT', name: 'GPT100', year: 2025 },
];

export const CATALOGUE: CatalogueGroup[] = [
  {
    category: 'Structure & Shelter',
    icon: '⛺',
    items: [
      {
        name: 'Marquee Walls - 3x3 (or equivalent)',
        sku: 'STR-01',
        unit: 'each',
        hold: 115,
        consumable: false,
        note: '',
        needs: {KT: 24, BSF: 100, AC: 24, WP: 16, WR: 37, HC: 33, PBRF: 8, RCR: 32, GPT: 115},
      },
      {
        name: 'Marquee - ST 3x3 (or equivalent)',
        sku: 'STR-02',
        unit: 'each',
        hold: 43,
        consumable: false,
        note: '',
        needs: {KT: 6, BB: 2, BSF: 38, AC: 8, WP: 12, WR: 15, HC: 20, PBRF: 4, RCR: 19, GPT: 43},
      },
      {
        name: 'WOW Structure (large dome)',
        sku: 'STR-03',
        unit: 'each',
        hold: 0,
        consumable: false,
        note: '',
        needs: {},
      },
    ],
  },
  {
    category: 'Anchoring & Weights',
    icon: '⚓',
    items: [
      {
        name: 'Ratchet Straps',
        sku: 'ANC-01',
        unit: 'each',
        hold: 136,
        consumable: false,
        note: '',
        needs: {BSF: 136, AC: 32, WP: 32, WR: 60, HC: 80, PBRF: 20, RCR: 76, GPT: 120},
      },
      {
        name: 'Pegs - Large',
        sku: 'ANC-02',
        unit: 'each',
        hold: 102,
        consumable: false,
        note: '',
        needs: {BSF: 102, AC: 16, HC: 52},
      },
      {
        name: 'Weights - Steel 20kg',
        sku: 'ANC-03',
        unit: 'each',
        hold: 100,
        consumable: false,
        note: '',
        needs: {KT: 24, BB: 20, BSF: 90, AC: 40, WP: 56, WR: 60, PBRF: 20, RCR: 16, GPT: 100},
      },
      {
        name: 'Sandbags',
        sku: 'ANC-04',
        unit: 'each',
        hold: 52,
        consumable: false,
        note: '',
        needs: {HC: 52, RCR: 32},
      },
      {
        name: 'Pegs - Small',
        sku: 'ANC-05',
        unit: 'each',
        hold: 24,
        consumable: false,
        note: '',
        needs: {WP: 10, HC: 8, GPT: 24},
      },
      {
        name: 'Weights - Concrete Blocks',
        sku: 'ANC-06',
        unit: 'each',
        hold: 0,
        consumable: false,
        note: '',
        needs: {},
      },
    ],
  },
  {
    category: 'Water & Ice',
    icon: '💧',
    items: [
      {
        name: 'Water Containers (20L equiv)',
        sku: 'WAT-01',
        unit: 'each',
        hold: 98,
        consumable: false,
        note: '',
        needs: {BB: 25, BSF: 72, AC: 8, WP: 6, WR: 37, PBRF: 8, GPT: 98},
      },
      {
        name: 'Pallets for IBCs',
        sku: 'WAT-02',
        unit: 'each',
        hold: 52,
        consumable: false,
        note: '',
        needs: {BSF: 52, PBRF: 3, GPT: 3},
      },
      {
        name: 'Esky / Cooler',
        sku: 'WAT-03',
        unit: 'each',
        hold: 26,
        consumable: false,
        note: '',
        needs: {KT: 4, BSF: 16, WR: 10, RCR: 7, GPT: 26},
      },
      {
        name: 'Spray Bottle / Backpack (Ice Water)',
        sku: 'WAT-04',
        unit: 'each',
        hold: 21,
        consumable: false,
        note: '',
        needs: {HC: 2, RCR: 1, GPT: 21},
      },
      {
        name: 'Plastic Tubs for Serving Ice',
        sku: 'WAT-05',
        unit: 'each',
        hold: 18,
        consumable: false,
        note: '',
        needs: {GPT: 18},
      },
      {
        name: 'IBC Pipe',
        sku: 'WAT-06',
        unit: 'each',
        hold: 13,
        consumable: false,
        note: '',
        needs: {BSF: 13, HC: 3, RCR: 2, GPT: 4},
      },
      {
        name: 'IBC Water Container (1000L)',
        sku: 'WAT-07',
        unit: 'each',
        hold: 13,
        consumable: false,
        note: '',
        needs: {BSF: 13, HC: 3, PBRF: 2, RCR: 2, GPT: 4},
      },
      {
        name: 'IBC Manifold',
        sku: 'WAT-08',
        unit: 'each',
        hold: 8,
        consumable: false,
        note: '',
        needs: {BSF: 8, GPT: 3},
      },
      {
        name: 'Hose & Fittings / Spray Nozzle',
        sku: 'WAT-09',
        unit: 'each',
        hold: 4,
        consumable: false,
        note: '',
        needs: {KT: 1, WP: 1, WR: 1, HC: 1, PBRF: 1, RCR: 1, GPT: 4},
      },
    ],
  },
  {
    category: 'Aid Station Kits',
    icon: '🧰',
    items: [
      {
        name: 'Primary Aid Station Kit (3 x Black Tubs)',
        sku: 'KIT-01',
        unit: 'each',
        hold: 7,
        consumable: false,
        note: '',
        needs: {BSF: 7, AC: 6, WP: 3, WR: 4},
      },
    ],
  },
  {
    category: 'Power & Cabling',
    icon: '🔌',
    items: [
      {
        name: 'Electrical Power Cable (2-3m)',
        sku: 'PWR-01',
        unit: 'each',
        hold: 35,
        consumable: false,
        note: '',
        needs: {KT: 2, BSF: 13, AC: 4, WP: 6, WR: 10, HC: 17, RCR: 16, GPT: 35},
      },
      {
        name: 'Electrical Cable (5m / 25m)',
        sku: 'PWR-02',
        unit: 'each',
        hold: 31,
        consumable: false,
        note: '',
        needs: {BSF: 15, AC: 4, WP: 6, WR: 2, GPT: 31},
      },
      {
        name: 'Extension Cable - 10m',
        sku: 'PWR-03',
        unit: 'each',
        hold: 23,
        consumable: false,
        note: '',
        needs: {BSF: 23, AC: 14, WP: 6, WR: 13, GPT: 20},
      },
      {
        name: 'Power Board',
        sku: 'PWR-04',
        unit: 'each',
        hold: 23,
        consumable: false,
        note: '',
        needs: {KT: 4, BB: 2, BSF: 10, AC: 14, WP: 8, WR: 12, HC: 9, RCR: 8, GPT: 23},
      },
      {
        name: 'Orange Cable Lead Cover',
        sku: 'PWR-05',
        unit: 'each',
        hold: 16,
        consumable: false,
        note: '',
        needs: {KT: 4, BSF: 14, AC: 16, WP: 12, WR: 12, HC: 8, RCR: 7, GPT: 14},
      },
      {
        name: 'Generator',
        sku: 'PWR-06',
        unit: 'each',
        hold: 14,
        consumable: false,
        note: '',
        needs: {BSF: 5, AC: 4, WP: 1, WR: 3, PBRF: 1, RCR: 3, GPT: 14},
      },
      {
        name: 'Cable Ties',
        sku: 'PWR-07',
        unit: 'pack',
        hold: 13,
        consumable: true,
        note: '',
        needs: {KT: 4, HC: 13, RCR: 11},
      },
      {
        name: 'USB Cable Set (Micro/C/Lightning)',
        sku: 'PWR-08',
        unit: 'each',
        hold: 10,
        consumable: false,
        note: '',
        needs: {BSF: 6, AC: 6, WP: 1, WR: 5, GPT: 10},
      },
      {
        name: 'USB Charge Dock',
        sku: 'PWR-09',
        unit: 'each',
        hold: 10,
        consumable: false,
        note: '',
        needs: {BSF: 6, AC: 6, WP: 3, WR: 5, GPT: 10},
      },
      {
        name: 'Extension Cable (5m+)',
        sku: 'PWR-10',
        unit: 'each',
        hold: 9,
        consumable: false,
        note: '',
        needs: {KT: 2, HC: 9, RCR: 8},
      },
      {
        name: 'Jerry Can (Fuel)',
        sku: 'PWR-11',
        unit: 'each',
        hold: 9,
        consumable: false,
        note: '',
        needs: {KT: 1, BSF: 1, AC: 4, WP: 1, WR: 3, HC: 3, RCR: 2, GPT: 9},
      },
      {
        name: 'Extension Cable - 20m Heavy Duty',
        sku: 'PWR-12',
        unit: 'each',
        hold: 8,
        consumable: false,
        note: '',
        needs: {KT: 4, BSF: 6, AC: 4, WP: 2, WR: 5, HC: 8, RCR: 8, GPT: 8},
      },
      {
        name: 'Large Generator (Hired)',
        sku: 'PWR-13',
        unit: 'each',
        hold: 6,
        consumable: false,
        note: '',
        needs: {BSF: 6},
      },
      {
        name: 'Power Electrical Cable (20m+)',
        sku: 'PWR-14',
        unit: 'each',
        hold: 5,
        consumable: false,
        note: '',
        needs: {GPT: 5},
      },
      {
        name: 'Extension Cable - 15 AMP',
        sku: 'PWR-15',
        unit: 'each',
        hold: 4,
        consumable: false,
        note: '',
        needs: {BSF: 2, HC: 2, RCR: 4, GPT: 2},
      },
      {
        name: 'Power Large Generator',
        sku: 'PWR-16',
        unit: 'each',
        hold: 0,
        consumable: false,
        note: '',
        needs: {},
      },
    ],
  },
  {
    category: 'Lighting',
    icon: '💡',
    items: [
      {
        name: 'Tripod Light - 240V',
        sku: 'LGT-01',
        unit: 'each',
        hold: 29,
        consumable: false,
        note: '',
        needs: {BSF: 17, AC: 8, WP: 2, WR: 4, GPT: 29},
      },
      {
        name: 'Strip Light',
        sku: 'LGT-02',
        unit: 'each',
        hold: 23,
        consumable: false,
        note: '',
        needs: {BSF: 17, AC: 8, WP: 6, WR: 10, HC: 11, RCR: 11, GPT: 23},
      },
      {
        name: 'Festoon Lighting (10m lengths)',
        sku: 'LGT-03',
        unit: 'each',
        hold: 12,
        consumable: false,
        note: '',
        needs: {BSF: 1, AC: 2, WP: 2, WR: 4, HC: 10, RCR: 10, GPT: 12},
      },
      {
        name: 'Tripod Light - Battery',
        sku: 'LGT-04',
        unit: 'each',
        hold: 7,
        consumable: false,
        note: '',
        needs: {BSF: 2, AC: 7, WP: 4, WR: 6, GPT: 6},
      },
      {
        name: 'Strobe Lights (Running Wild)',
        sku: 'LGT-05',
        unit: 'each',
        hold: 4,
        consumable: false,
        note: '',
        needs: {AC: 4, WR: 4},
      },
      {
        name: 'Yellow Hazard Light',
        sku: 'LGT-06',
        unit: 'each',
        hold: 2,
        consumable: false,
        note: '',
        needs: {AC: 1, WP: 2, WR: 2},
      },
      {
        name: 'Stand Light',
        sku: 'LGT-07',
        unit: 'each',
        hold: 1,
        consumable: false,
        note: '',
        needs: {HC: 1, RCR: 1},
      },
    ],
  },
  {
    category: 'Cooking & Heating',
    icon: '🔥',
    items: [
      {
        name: 'Gas Bottle',
        sku: 'CKG-01',
        unit: 'each',
        hold: 10,
        consumable: false,
        note: '',
        needs: {BSF: 5, AC: 4, WP: 3, WR: 5, HC: 5, GPT: 10},
      },
      {
        name: 'Gas Stove',
        sku: 'CKG-02',
        unit: 'each',
        hold: 10,
        consumable: false,
        note: '',
        needs: {BSF: 5, AC: 4, WP: 3, WR: 3, HC: 2, GPT: 10},
      },
      {
        name: 'Kettle - Stove Top',
        sku: 'CKG-03',
        unit: 'each',
        hold: 10,
        consumable: false,
        note: '',
        needs: {AC: 2, WP: 6, WR: 3, HC: 2, GPT: 10},
      },
      {
        name: 'Toastie / Jaffle Maker',
        sku: 'CKG-04',
        unit: 'each',
        hold: 7,
        consumable: false,
        note: '',
        needs: {BSF: 6, AC: 5, HC: 1, GPT: 7},
      },
      {
        name: 'Candle for Bain Marie',
        sku: 'CKG-05',
        unit: 'each',
        hold: 6,
        consumable: false,
        note: '',
        needs: {GPT: 6},
      },
      {
        name: 'Electric Hot Water Urn',
        sku: 'CKG-06',
        unit: 'each',
        hold: 6,
        consumable: false,
        note: '',
        needs: {BSF: 6, AC: 1, WP: 1, WR: 3, HC: 3, GPT: 3},
      },
      {
        name: 'Gas Heater',
        sku: 'CKG-07',
        unit: 'each',
        hold: 5,
        consumable: false,
        note: '',
        needs: {HC: 5},
      },
      {
        name: 'Milo / Tea / Coffee / Sugar / Salt',
        sku: 'CKG-08',
        unit: 'each',
        hold: 5,
        consumable: true,
        note: '',
        needs: {HC: 5},
      },
      {
        name: 'Kettle - Electric',
        sku: 'CKG-09',
        unit: 'each',
        hold: 4,
        consumable: false,
        note: '',
        needs: {AC: 4, WR: 1, HC: 2},
      },
      {
        name: 'Bain Marie',
        sku: 'CKG-10',
        unit: 'each',
        hold: 1,
        consumable: false,
        note: '',
        needs: {GPT: 1},
      },
    ],
  },
  {
    category: 'Serving & Catering',
    icon: '🍽',
    items: [
      {
        name: 'Sporks / Cutlery',
        sku: 'SRV-01',
        unit: 'each',
        hold: 50,
        consumable: false,
        note: '',
        needs: {BSF: 24, AC: 5, WP: 6, WR: 4, HC: 8, GPT: 50},
      },
      {
        name: 'Insulated Hot Cups',
        sku: 'SRV-02',
        unit: 'each',
        hold: 44,
        consumable: false,
        note: '',
        needs: {BSF: 12, AC: 5, WP: 8, WR: 10, HC: 4, GPT: 44},
      },
      {
        name: 'Small Freezer Bags',
        sku: 'SRV-03',
        unit: 'pack',
        hold: 40,
        consumable: true,
        note: '',
        needs: {KT: 20, HC: 40, RCR: 30},
      },
      {
        name: 'Industrial Foil - 1 Roll per 20 P',
        sku: 'SRV-04',
        unit: 'roll',
        hold: 34,
        consumable: true,
        note: '',
        needs: {GPT: 34},
      },
      {
        name: 'Serving Jugs (2L, marked)',
        sku: 'SRV-05',
        unit: 'each',
        hold: 21,
        consumable: false,
        note: '',
        needs: {KT: 6, BB: 4, BSF: 5, WR: 19, HC: 14, PBRF: 2, RCR: 10, GPT: 21},
      },
      {
        name: 'Tongs',
        sku: 'SRV-06',
        unit: 'each',
        hold: 16,
        consumable: false,
        note: '',
        needs: {KT: 8, HC: 16, RCR: 12},
      },
      {
        name: 'Tupperware Containers',
        sku: 'SRV-07',
        unit: 'each',
        hold: 16,
        consumable: false,
        note: '',
        needs: {KT: 8, BB: 1, HC: 16, RCR: 12},
      },
      {
        name: 'Tupperware Lids',
        sku: 'SRV-08',
        unit: 'each',
        hold: 16,
        consumable: false,
        note: '',
        needs: {KT: 8, HC: 16, RCR: 12},
      },
      {
        name: 'Aluminium Foil',
        sku: 'SRV-09',
        unit: 'roll',
        hold: 8,
        consumable: true,
        note: '',
        needs: {HC: 8},
      },
      {
        name: 'Chopping / Cutting Board',
        sku: 'SRV-10',
        unit: 'each',
        hold: 8,
        consumable: false,
        note: '',
        needs: {KT: 4, BB: 2, HC: 8, PBRF: 1, RCR: 6},
      },
      {
        name: 'Electrolyte Measuring Cup',
        sku: 'SRV-11',
        unit: 'each',
        hold: 8,
        consumable: false,
        note: '',
        needs: {KT: 4, WR: 5, HC: 8, RCR: 6},
      },
      {
        name: 'Knives',
        sku: 'SRV-12',
        unit: 'each',
        hold: 8,
        consumable: false,
        note: '',
        needs: {KT: 4, HC: 8, RCR: 6},
      },
      {
        name: 'Serving Bowls',
        sku: 'SRV-13',
        unit: 'each',
        hold: 8,
        consumable: false,
        note: '',
        needs: {KT: 4, BB: 2, HC: 8, RCR: 6},
      },
      {
        name: 'Serving Platters',
        sku: 'SRV-14',
        unit: 'each',
        hold: 8,
        consumable: false,
        note: '',
        needs: {KT: 4, HC: 8, RCR: 6},
      },
      {
        name: 'Paper Bib Log Sheets + Clipboard',
        sku: 'SRV-15',
        unit: 'each',
        hold: 4,
        consumable: false,
        note: '',
        needs: {WR: 4},
      },
      {
        name: 'Industrial Foil - 1 Roll per 20 Potatoes',
        sku: 'SRV-16',
        unit: 'roll',
        hold: 1,
        consumable: true,
        note: '',
        needs: {BSF: 1},
      },
      {
        name: 'Stirring Spoon',
        sku: 'SRV-17',
        unit: 'each',
        hold: 1,
        consumable: false,
        note: '',
        needs: {KT: 1, HC: 1},
      },
      {
        name: 'Spatula',
        sku: 'SRV-18',
        unit: 'each',
        hold: 0,
        consumable: false,
        note: '',
        needs: {},
      },
    ],
  },
  {
    category: 'Hygiene & Consumables',
    icon: '🧼',
    items: [
      {
        name: 'Toilet Paper',
        sku: 'HYG-01',
        unit: 'roll',
        hold: 144,
        consumable: true,
        note: '',
        needs: {KT: 48, BB: 10, BSF: 9, AC: 1, WP: 1, WR: 2, PBRF: 2, RCR: 144, GPT: 25},
      },
      {
        name: 'Sunscreen',
        sku: 'HYG-02',
        unit: 'each',
        hold: 22,
        consumable: true,
        note: '',
        needs: {KT: 18, BB: 1, RCR: 22},
      },
      {
        name: 'Hand Sanitiser',
        sku: 'HYG-03',
        unit: 'each',
        hold: 16,
        consumable: true,
        note: '',
        needs: {KT: 12, BB: 1, RCR: 16},
      },
      {
        name: 'Sponges',
        sku: 'HYG-04',
        unit: 'each',
        hold: 16,
        consumable: true,
        note: '',
        needs: {KT: 8, HC: 16, RCR: 12},
      },
      {
        name: 'Paper Towel / Chux',
        sku: 'HYG-05',
        unit: 'each',
        hold: 12,
        consumable: true,
        note: '',
        needs: {KT: 4, BB: 1, WR: 5, HC: 12, RCR: 8},
      },
      {
        name: 'Emergency Ponchos',
        sku: 'HYG-06',
        unit: 'each',
        hold: 4,
        consumable: true,
        note: '',
        needs: {KT: 2, HC: 4, RCR: 3},
      },
      {
        name: 'Gloves',
        sku: 'HYG-07',
        unit: 'each',
        hold: 4,
        consumable: true,
        note: '',
        needs: {KT: 2, HC: 4, RCR: 3},
      },
      {
        name: 'Sanitiser Cleaning Spray (Spray & Wipe)',
        sku: 'HYG-08',
        unit: 'each',
        hold: 4,
        consumable: true,
        note: '',
        needs: {KT: 2, BB: 1, HC: 4, RCR: 3},
      },
      {
        name: 'Scrubbing Brush',
        sku: 'HYG-09',
        unit: 'each',
        hold: 4,
        consumable: false,
        note: '',
        needs: {KT: 2, HC: 4, RCR: 3},
      },
      {
        name: 'Female Sanitary Items',
        sku: 'HYG-10',
        unit: 'each',
        hold: 3,
        consumable: true,
        note: '',
        needs: {KT: 2, RCR: 3},
      },
    ],
  },
  {
    category: 'Medical & Welfare',
    icon: '🚑',
    items: [
      {
        name: 'Blankets / Space Blankets',
        sku: 'MED-01',
        unit: 'each',
        hold: 100,
        consumable: false,
        note: '',
        needs: {WR: 22, GPT: 100},
      },
      {
        name: 'Camp Stretcher / Folding Bed',
        sku: 'MED-02',
        unit: 'each',
        hold: 20,
        consumable: false,
        note: '',
        needs: {WR: 3, GPT: 20},
      },
      {
        name: 'Picnic Blankets',
        sku: 'MED-03',
        unit: 'each',
        hold: 20,
        consumable: false,
        note: '',
        needs: {BSF: 1, HC: 10, RCR: 10, GPT: 20},
      },
      {
        name: 'First Aid Kit',
        sku: 'MED-04',
        unit: 'each',
        hold: 4,
        consumable: false,
        note: '',
        needs: {KT: 2, BB: 1, AC: 3, HC: 4, RCR: 3},
      },
      {
        name: 'Sleeping Bag',
        sku: 'MED-05',
        unit: 'each',
        hold: 4,
        consumable: false,
        note: '',
        needs: {WR: 4},
      },
      {
        name: 'Snake Bite PIB Kit',
        sku: 'MED-06',
        unit: 'each',
        hold: 0,
        consumable: false,
        note: '',
        needs: {},
      },
    ],
  },
  {
    category: 'Waste Management',
    icon: '🗑',
    items: [
      {
        name: 'Bins - Large Round Black',
        sku: 'WST-01',
        unit: 'each',
        hold: 14,
        consumable: false,
        note: '',
        needs: {BSF: 14, WR: 8, HC: 10, PBRF: 10, RCR: 8},
      },
      {
        name: 'Bin Bags (large / roll)',
        sku: 'WST-02',
        unit: 'roll',
        hold: 12,
        consumable: true,
        note: '',
        needs: {KT: 8, BB: 3, BSF: 1, WP: 2, WR: 12, HC: 12, RCR: 10, GPT: 4},
      },
    ],
  },
  {
    category: 'Course Marking & Traffic',
    icon: '🚧',
    items: [
      {
        name: 'Marshal / Volunteer Vests',
        sku: 'CRS-01',
        unit: 'each',
        hold: 100,
        consumable: false,
        note: '',
        needs: {BB: 6, AC: 25, WP: 100, WR: 38},
      },
      {
        name: 'Witches Hats / Cones',
        sku: 'CRS-02',
        unit: 'each',
        hold: 100,
        consumable: false,
        note: '',
        needs: {KT: 40, BB: 10, BSF: 100, AC: 20, WP: 25, WR: 20, HC: 58, PBRF: 30, RCR: 58, GPT: 25},
      },
      {
        name: 'Marker Flags & Course Signage Set',
        sku: 'CRS-03',
        unit: 'each',
        hold: 50,
        consumable: false,
        note: '',
        needs: {BB: 2, WP: 50},
      },
      {
        name: 'Traffic Bollards and Bases',
        sku: 'CRS-04',
        unit: 'each',
        hold: 32,
        consumable: false,
        note: '',
        needs: {BSF: 9, AC: 9, WP: 5, WR: 10, GPT: 32},
      },
      {
        name: 'Wooden Stakes',
        sku: 'CRS-05',
        unit: 'each',
        hold: 30,
        consumable: true,
        note: '',
        needs: {BB: 12, WP: 1, WR: 30},
      },
      {
        name: 'Glow Sticks',
        sku: 'CRS-06',
        unit: 'pack',
        hold: 24,
        consumable: true,
        note: '',
        needs: {AC: 24},
      },
      {
        name: 'Bunting (lengths)',
        sku: 'CRS-07',
        unit: 'roll',
        hold: 22,
        consumable: true,
        note: '',
        needs: {BSF: 6, AC: 6, WR: 9, GPT: 22},
      },
      {
        name: 'Marshal Point signs and stakes',
        sku: 'CRS-08',
        unit: 'each',
        hold: 10,
        consumable: false,
        note: '',
        needs: {PBRF: 10},
      },
      {
        name: 'Road Signage (EVENT IN PROGRESS)',
        sku: 'CRS-09',
        unit: 'each',
        hold: 6,
        consumable: false,
        note: '',
        needs: {BSF: 1, AC: 6, WP: 4, WR: 4},
      },
      {
        name: 'Runners on Road Signs (Running Wild)',
        sku: 'CRS-10',
        unit: 'each',
        hold: 4,
        consumable: false,
        note: '',
        needs: {AC: 2, WP: 1, WR: 4},
      },
    ],
  },
  {
    category: 'Comms & AV',
    icon: '📡',
    items: [
      {
        name: 'Starlink',
        sku: 'COM-01',
        unit: 'each',
        hold: 13,
        consumable: false,
        note: '',
        needs: {BSF: 6, AC: 4, WP: 3, WR: 4, HC: 6, PBRF: 1, RCR: 5, GPT: 13},
      },
      {
        name: 'Battery Pack',
        sku: 'COM-02',
        unit: 'each',
        hold: 3,
        consumable: false,
        note: '',
        needs: {WP: 2, WR: 3},
      },
      {
        name: 'Bluetooth Speaker',
        sku: 'COM-03',
        unit: 'each',
        hold: 3,
        consumable: false,
        note: '',
        needs: {HC: 3, RCR: 2},
      },
      {
        name: 'PA System / VONYX + Mic + Stand',
        sku: 'COM-04',
        unit: 'each',
        hold: 3,
        consumable: false,
        note: '',
        needs: {BB: 1, BSF: 3, AC: 1, WP: 1, WR: 1, RCR: 1, GPT: 2},
      },
      {
        name: 'Internet Dongle',
        sku: 'COM-05',
        unit: 'each',
        hold: 1,
        consumable: false,
        note: '',
        needs: {BSF: 1, AC: 1, WR: 1, RCR: 1, GPT: 1},
      },
      {
        name: 'Satellite Phone (NOT USED)',
        sku: 'COM-06',
        unit: 'each',
        hold: 0,
        consumable: false,
        note: '',
        needs: {},
      },
    ],
  },
  {
    category: 'Event Village & Branding',
    icon: '🎪',
    items: [
      {
        name: 'Mesh Banner Toggles',
        sku: 'VIL-01',
        unit: 'each',
        hold: 50,
        consumable: false,
        note: '',
        needs: {BSF: 1, WP: 1, WR: 1, HC: 12, RCR: 12, GPT: 50},
      },
      {
        name: 'Crowd Barriers',
        sku: 'VIL-02',
        unit: 'each',
        hold: 39,
        consumable: false,
        note: '',
        needs: {BSF: 39, WR: 20, HC: 6, GPT: 34},
      },
      {
        name: 'Portable Toilets',
        sku: 'VIL-03',
        unit: 'each',
        hold: 38,
        consumable: false,
        note: '',
        needs: {RCR: 14, GPT: 38},
      },
      {
        name: 'Track Mat / Carpet',
        sku: 'VIL-04',
        unit: 'roll',
        hold: 34,
        consumable: false,
        note: '',
        needs: {KT: 4, BB: 6, BSF: 1, AC: 1, WP: 4, WR: 1, RCR: 34, GPT: 1},
      },
      {
        name: 'Pig Tails (crowd line)',
        sku: 'VIL-05',
        unit: 'each',
        hold: 20,
        consumable: false,
        note: '',
        needs: {WP: 10, WR: 20},
      },
      {
        name: 'Banners / Teardrop Banners / Sponsor Flags',
        sku: 'VIL-06',
        unit: 'each',
        hold: 18,
        consumable: false,
        note: '',
        needs: {KT: 4, BB: 8, BSF: 1, AC: 1, WP: 8, WR: 4, HC: 18, RCR: 18, GPT: 6},
      },
      {
        name: 'ASICS Umbrellas',
        sku: 'VIL-07',
        unit: 'each',
        hold: 10,
        consumable: false,
        note: '',
        needs: {GPT: 10},
      },
      {
        name: 'Umbrella Bases',
        sku: 'VIL-08',
        unit: 'each',
        hold: 10,
        consumable: false,
        note: '',
        needs: {BSF: 1, HC: 6, RCR: 6, GPT: 10},
      },
      {
        name: 'Inflatable Arch Pump',
        sku: 'VIL-09',
        unit: 'each',
        hold: 8,
        consumable: false,
        note: '',
        needs: {KT: 1, BSF: 1, AC: 1, WP: 1, WR: 1, HC: 2, RCR: 2, GPT: 8},
      },
      {
        name: 'A-Frames (Village Instructions)',
        sku: 'VIL-10',
        unit: 'each',
        hold: 6,
        consumable: false,
        note: '',
        needs: {BSF: 1, WR: 6, HC: 6, RCR: 6},
      },
      {
        name: 'Finish Gantry (Running Wild)',
        sku: 'VIL-11',
        unit: 'each',
        hold: 3,
        consumable: false,
        note: '',
        needs: {BSF: 1, AC: 1, WP: 1, WR: 1, GPT: 3},
      },
      {
        name: 'Entry / Exit Signs',
        sku: 'VIL-12',
        unit: 'each',
        hold: 2,
        consumable: false,
        note: '',
        needs: {WR: 2},
      },
      {
        name: 'Inflatable Arch',
        sku: 'VIL-13',
        unit: 'each',
        hold: 2,
        consumable: false,
        note: '',
        needs: {KT: 1, BB: 1, BSF: 1, HC: 1, RCR: 2, GPT: 1},
      },
      {
        name: 'Picket Fence',
        sku: 'VIL-14',
        unit: 'each',
        hold: 2,
        consumable: false,
        note: '',
        needs: {BSF: 1, GPT: 2},
      },
      {
        name: 'Toilet Signage',
        sku: 'VIL-15',
        unit: 'each',
        hold: 2,
        consumable: false,
        note: '',
        needs: {BSF: 1, AC: 1, WR: 2, GPT: 2},
      },
      {
        name: 'Signage - Alpine Challenge Welcome to Alpine Challenge banner - in a large tube Also Race HQ pull up banner',
        sku: 'VIL-16',
        unit: 'each',
        hold: 0,
        consumable: false,
        note: '',
        needs: {},
      },
    ],
  },
  {
    category: 'Registration, Merch & Timing',
    icon: '⏱',
    items: [
      {
        name: 'Safety Pins',
        sku: 'REG-01',
        unit: 'pack',
        hold: 3600,
        consumable: true,
        note: '',
        needs: {KT: 1600, BSF: 1, HC: 3600, RCR: 3600},
      },
      {
        name: 'Batteries (AA)',
        sku: 'REG-02',
        unit: 'pack',
        hold: 20,
        consumable: true,
        note: '',
        needs: {BSF: 10, AC: 10, WP: 10, WR: 20, GPT: 10},
      },
      {
        name: 'Batteries (AAA)',
        sku: 'REG-03',
        unit: 'pack',
        hold: 20,
        consumable: true,
        note: '',
        needs: {BSF: 10, AC: 10, WP: 10, WR: 20, GPT: 10},
      },
      {
        name: 'Finisher Medals',
        sku: 'REG-04',
        unit: 'each',
        hold: 6,
        consumable: true,
        note: '',
        needs: {BSF: 1, AC: 1, WP: 6, WR: 1, RCR: 1, GPT: 1},
      },
      {
        name: 'Merchandise',
        sku: 'REG-05',
        unit: 'each',
        hold: 5,
        consumable: true,
        note: '',
        needs: {BSF: 1, AC: 1, WP: 1, WR: 1, RCR: 1, GPT: 5},
      },
      {
        name: 'Alpine Timing Box / Mats',
        sku: 'REG-06',
        unit: 'each',
        hold: 4,
        consumable: false,
        note: '',
        needs: {WR: 4},
      },
      {
        name: 'End-of-Day Stocktake QR Poster',
        sku: 'REG-07',
        unit: 'each',
        hold: 4,
        consumable: false,
        note: '',
        needs: {WR: 4},
      },
      {
        name: 'Station Document Pack',
        sku: 'REG-08',
        unit: 'each',
        hold: 4,
        consumable: false,
        note: '',
        needs: {WR: 4},
      },
      {
        name: 'Laminator Sheets',
        sku: 'REG-09',
        unit: 'each',
        hold: 2,
        consumable: true,
        note: '',
        needs: {BSF: 1, GPT: 2},
      },
      {
        name: 'Merch - iPad & Square Reader',
        sku: 'REG-10',
        unit: 'each',
        hold: 2,
        consumable: false,
        note: '',
        needs: {BSF: 1, WP: 1, WR: 1, HC: 2, RCR: 2, GPT: 2},
      },
      {
        name: 'Paper (packs)',
        sku: 'REG-11',
        unit: 'each',
        hold: 2,
        consumable: true,
        note: '',
        needs: {KT: 2, BSF: 1, HC: 2, RCR: 2, GPT: 2},
      },
      {
        name: 'Registration Lists / Distance Signs',
        sku: 'REG-12',
        unit: 'each',
        hold: 2,
        consumable: false,
        note: '',
        needs: {BSF: 1, WP: 1, WR: 1, HC: 2, RCR: 2, GPT: 2},
      },
      {
        name: 'Laminator',
        sku: 'REG-13',
        unit: 'each',
        hold: 1,
        consumable: false,
        note: '',
        needs: {BSF: 1, GPT: 1},
      },
      {
        name: 'Printer',
        sku: 'REG-14',
        unit: 'each',
        hold: 1,
        consumable: false,
        note: '',
        needs: {KT: 1, BSF: 1, AC: 1, WP: 1, WR: 1, HC: 1, RCR: 1},
      },
      {
        name: 'Printer Ink',
        sku: 'REG-15',
        unit: 'each',
        hold: 1,
        consumable: true,
        note: '',
        needs: {KT: 1, BSF: 1, AC: 1, WP: 1, WR: 1, HC: 1, RCR: 1, GPT: 1},
      },
      {
        name: 'Prizes and Trophies',
        sku: 'REG-16',
        unit: 'each',
        hold: 1,
        consumable: false,
        note: '',
        needs: {AC: 1, WP: 1, WR: 1},
      },
      {
        name: 'Stationery (folders/pens/blutack)',
        sku: 'REG-17',
        unit: 'each',
        hold: 1,
        consumable: true,
        note: '',
        needs: {WR: 1},
      },
      {
        name: 'Timing Clock / Frame',
        sku: 'REG-18',
        unit: 'each',
        hold: 1,
        consumable: false,
        note: '',
        needs: {BB: 1},
      },
      {
        name: 'box with laminator, printer, stationary',
        sku: 'REG-19',
        unit: 'each',
        hold: 1,
        consumable: false,
        note: '',
        needs: {PBRF: 1},
      },
      {
        name: 'PLBs',
        sku: 'REG-20',
        unit: 'each',
        hold: 0,
        consumable: false,
        note: '',
        needs: {},
      },
      {
        name: 'Race Bibs',
        sku: 'REG-21',
        unit: 'each',
        hold: 0,
        consumable: true,
        note: '',
        needs: {},
      },
      {
        name: 'Start - Finish Box / Pins / Bibs / Thick Texta / white lables Box',
        sku: 'REG-22',
        unit: 'each',
        hold: 0,
        consumable: false,
        note: '',
        needs: {},
      },
    ],
  },
  {
    category: 'Tools & Hardware',
    icon: '🔧',
    items: [
      {
        name: 'Scissors / Snippers',
        sku: 'TLS-01',
        unit: 'each',
        hold: 9,
        consumable: false,
        note: '',
        needs: {KT: 7, HC: 9, RCR: 8},
      },
      {
        name: 'Hammer / Mallet',
        sku: 'TLS-02',
        unit: 'each',
        hold: 4,
        consumable: false,
        note: '',
        needs: {KT: 1, BB: 1, BSF: 2, AC: 2, WR: 1, HC: 4, GPT: 3},
      },
      {
        name: 'Gaffa Tape',
        sku: 'TLS-03',
        unit: 'roll',
        hold: 3,
        consumable: true,
        note: '',
        needs: {KT: 2, RCR: 3},
      },
      {
        name: 'Toolbox',
        sku: 'TLS-04',
        unit: 'each',
        hold: 2,
        consumable: false,
        note: '',
        needs: {BB: 1, WP: 1, WR: 2, PBRF: 1, RCR: 1},
      },
      {
        name: 'Hand Trolley',
        sku: 'TLS-05',
        unit: 'each',
        hold: 1,
        consumable: false,
        note: '',
        needs: {KT: 1},
      },
    ],
  },
  {
    category: 'Fire (where permitted)',
    icon: '🪵',
    items: [
      {
        name: 'Matches',
        sku: 'FIR-01',
        unit: 'each',
        hold: 4,
        consumable: true,
        note: '',
        needs: {HC: 4},
      },
      {
        name: 'Firestarters',
        sku: 'FIR-02',
        unit: 'each',
        hold: 3,
        consumable: true,
        note: '',
        needs: {AC: 3, GPT: 1},
      },
      {
        name: 'Kindling',
        sku: 'FIR-03',
        unit: 'bag',
        hold: 3,
        consumable: true,
        note: '',
        needs: {AC: 3, GPT: 1},
      },
      {
        name: 'Firewood',
        sku: 'FIR-04',
        unit: 'bag',
        hold: 2,
        consumable: true,
        note: '',
        needs: {AC: 2, GPT: 2},
      },
    ],
  },
  {
    category: 'Cold Chain & Drop Bags',
    icon: '🧊',
    items: [
      {
        name: 'Drop Bag Crates / Tubs',
        sku: 'CLD-01',
        unit: 'each',
        hold: 6,
        consumable: false,
        note: '',
        needs: {WR: 6},
      },
      {
        name: 'Coolroom / Coolroom Trailer',
        sku: 'CLD-02',
        unit: 'each',
        hold: 2,
        consumable: false,
        note: '',
        needs: {BSF: 2, RCR: 1},
      },
      {
        name: 'Drop Bag Tarp / Cover',
        sku: 'CLD-03',
        unit: 'each',
        hold: 2,
        consumable: false,
        note: '',
        needs: {WR: 2},
      },
      {
        name: 'Drop Bags',
        sku: 'CLD-04',
        unit: 'each',
        hold: 0,
        consumable: true,
        note: '',
        needs: {},
      },
      {
        name: 'Small Freezer',
        sku: 'CLD-05',
        unit: 'each',
        hold: 0,
        consumable: false,
        note: '',
        needs: {},
      },
    ],
  },
  {
    category: 'Furniture & Site Equipment',
    icon: '🪑',
    items: [
      {
        name: 'Trestle Tables',
        sku: 'FRN-01',
        unit: 'each',
        hold: 155,
        consumable: false,
        note: '',
        needs: {BB: 2, BSF: 155, AC: 19, WP: 26, WR: 28, HC: 32, PBRF: 14, RCR: 38, GPT: 99},
      },
      {
        name: 'Chairs - Plastic Bistro',
        sku: 'FRN-02',
        unit: 'each',
        hold: 150,
        consumable: false,
        note: '',
        needs: {BSF: 150, HC: 20, RCR: 20, GPT: 130},
      },
      {
        name: 'Table Cloths',
        sku: 'FRN-03',
        unit: 'each',
        hold: 45,
        consumable: false,
        note: '',
        needs: {KT: 10, BB: 2, BSF: 12, AC: 19, WP: 12, WR: 28, PBRF: 12, GPT: 45},
      },
      {
        name: 'Tarps',
        sku: 'FRN-04',
        unit: 'each',
        hold: 28,
        consumable: false,
        note: '',
        needs: {BSF: 7, AC: 6, WR: 13, HC: 13, RCR: 10, GPT: 28},
      },
      {
        name: 'Volunteer Shirts',
        sku: 'FRN-05',
        unit: 'each',
        hold: 15,
        consumable: false,
        note: '',
        needs: {BB: 15},
      },
      {
        name: 'Chairs - Camping / Folding',
        sku: 'FRN-06',
        unit: 'each',
        hold: 12,
        consumable: false,
        note: '',
        needs: {AC: 10, WP: 8, WR: 12, HC: 6, RCR: 4},
      },
      {
        name: 'Lounge Chairs',
        sku: 'FRN-07',
        unit: 'each',
        hold: 10,
        consumable: false,
        note: '',
        needs: {BSF: 1, HC: 8, RCR: 8, GPT: 10},
      },
      {
        name: 'Inflatable Pillar',
        sku: 'FRN-08',
        unit: 'each',
        hold: 2,
        consumable: false,
        note: '',
        needs: {BSF: 1, HC: 2, RCR: 2, GPT: 2},
      },
      {
        name: 'Backpack',
        sku: 'FRN-09',
        unit: 'each',
        hold: 1,
        consumable: false,
        note: '',
        needs: {BB: 1},
      },
      {
        name: 'Tent / Pole / Chair',
        sku: 'FRN-10',
        unit: 'each',
        hold: 1,
        consumable: false,
        note: '',
        needs: {BB: 1},
      },
    ],
  },
  {
    category: 'Other / Review',
    icon: '📦',
    items: [
      {
        name: 'Kids Activity Kit (colouring, games)',
        sku: 'OTH-01',
        unit: 'each',
        hold: 250,
        consumable: true,
        note: '',
        needs: {BSF: 1, RCR: 1, GPT: 250},
      },
      {
        name: 'International / Participant / Presentation Flags',
        sku: 'OTH-02',
        unit: 'each',
        hold: 50,
        consumable: false,
        note: '',
        needs: {GPT: 50},
      },
      {
        name: 'Flag Poles',
        sku: 'OTH-03',
        unit: 'each',
        hold: 25,
        consumable: false,
        note: '',
        needs: {GPT: 25},
      },
      {
        name: 'Shoe Wash Kit',
        sku: 'OTH-04',
        unit: 'each',
        hold: 13,
        consumable: false,
        note: '',
        needs: {GPT: 13},
      },
      {
        name: 'Ice Baths (DOPE)',
        sku: 'OTH-05',
        unit: 'each',
        hold: 5,
        consumable: false,
        note: '',
        needs: {GPT: 5},
      },
      {
        name: 'Finisher Tape',
        sku: 'OTH-06',
        unit: 'roll',
        hold: 2,
        consumable: true,
        note: '',
        needs: {PBRF: 2},
      },
      {
        name: 'Registration Boxes',
        sku: 'OTH-07',
        unit: 'each',
        hold: 2,
        consumable: false,
        note: '',
        needs: {PBRF: 2},
      },
      {
        name: 'Running Wild - Misc Course Signs',
        sku: 'OTH-08',
        unit: 'each',
        hold: 2,
        consumable: false,
        note: '',
        needs: {AC: 2},
      },
      {
        name: 'ASICS Vehicle',
        sku: 'OTH-09',
        unit: 'each',
        hold: 1,
        consumable: false,
        note: '',
        needs: {BSF: 1, HC: 1, RCR: 1, GPT: 1},
      },
      {
        name: 'Drill and Charger',
        sku: 'OTH-10',
        unit: 'each',
        hold: 1,
        consumable: false,
        note: '',
        needs: {PBRF: 1},
      },
      {
        name: 'Electrical Leads (boxed, check)',
        sku: 'OTH-11',
        unit: 'each',
        hold: 1,
        consumable: false,
        note: '',
        needs: {PBRF: 1},
      },
      {
        name: 'Tap Key',
        sku: 'OTH-12',
        unit: 'each',
        hold: 1,
        consumable: false,
        note: '',
        needs: {PBRF: 1},
      },
      {
        name: 'Course & Village Signage (misc)',
        sku: 'OTH-13',
        unit: 'each',
        hold: 0,
        consumable: false,
        note: '',
        needs: {},
      },
      {
        name: 'Cups (bulk)',
        sku: 'OTH-14',
        unit: 'each',
        hold: 0,
        consumable: true,
        note: '',
        needs: {},
      },
    ],
  },
];
