/**
 * Hounslow Classic 2026: starting packlists and food plan.
 *
 * Two sources, both the crew's own documents:
 *
 * `HOUNSLOW_PACKLISTS` is the 2025 Aid Station Run Sheets (vFinal) — the
 * equipment matrix for the five service points, translated onto the warehouse
 * catalogue by item name. Quantities are last year's plan, seeded as required
 * amounts on draft packlists for this year's stations to be corrected from.
 *
 * `HOUNSLOW_CONSUMPTION` is the HC 2026 consumption planner, one rule per
 * station per race exactly as the sheet keys them: a marathon runner and a
 * 17k runner eat differently at the same table. With the marathon on the
 * Saturday and the 17k and kids on the Sunday, the plan falls out by day.
 */

export interface HounslowPackLine {
  /** Exact catalogue item name — a test keeps these honest. */
  item: string;
  qty: number;
  note?: string;
}

export interface HounslowPacklist {
  /** Destination name, matching the hc26 entry in eventSeed.ts. */
  station: string;
  lines: HounslowPackLine[];
}

const SANITISER = { item: 'Hand Sanitiser', qty: 5, note: '4 × 50 ml Dettol + 1 large pump' };
const SNIPS = { item: 'Scissors / Snippers', qty: 3, note: '2 scissors + 1 snips' };
const SPEAKER = { item: 'Bluetooth Speaker', qty: 1, note: 'Aid Station Team Leader to provide' };

/** The black-box kit every staffed station carried in 2025. */
const STATION_KIT: HounslowPackLine[] = [
  { item: 'Aluminium Foil', qty: 2 },
  { item: 'Bowls (eating)', qty: 2 },
  { item: 'Forks (box)', qty: 1 },
  { item: 'Cable Ties', qty: 2 },
  { item: 'Chopping / Cutting Board', qty: 2 },
  { item: 'Emergency Ponchos', qty: 1 },
  { item: 'Female Sanitary Items', qty: 1 },
  { item: 'First Aid Kit', qty: 1 },
  { item: 'Gaffa Tape', qty: 1 },
  { item: 'Gloves', qty: 1 },
  SANITISER,
  { item: 'Knives', qty: 2 },
  { item: 'Bin Bags (large / roll)', qty: 2 },
  { item: 'Electrolyte Measuring Cup', qty: 2 },
  { item: 'Sanitiser Cleaning Spray (Spray & Wipe)', qty: 1 },
  SNIPS,
  { item: 'Scrubbing Brush', qty: 1 },
  { item: 'Serving Bowls', qty: 2 },
  { item: 'Serving Platters', qty: 2 },
  { item: 'Small Freezer Bags', qty: 10 },
  { item: 'Sponges', qty: 4 },
  { item: 'Stirring Spoon', qty: 1 },
  { item: 'Sunscreen', qty: 4 },
  { item: 'Tongs', qty: 4 },
  { item: 'Tupperware Containers', qty: 4 },
  { item: 'Tupperware Lids', qty: 4 },
];

/** The hot-food setup Perrys and the Pinnacles both ran in 2025. */
const HOT_FOOD_KIT: HounslowPackLine[] = [
  { item: 'Toastie / Jaffle Maker', qty: 1 },
  { item: 'Kettle - Electric', qty: 1 },
  { item: 'Electric Hot Water Urn', qty: 1 },
  { item: 'Gas Bottle', qty: 1 },
  { item: 'Gas Heater', qty: 1 },
  { item: 'Gas Stove', qty: 1 },
  { item: 'Kettle - Stove Top', qty: 1 },
  { item: 'Insulated Hot Cups', qty: 1, note: 'Box of 500' },
  { item: 'Matches', qty: 1 },
  { item: 'Milo', qty: 1 },
  { item: 'Sporks / Cutlery', qty: 4, note: '4 packs of 50' },
];

export const HOUNSLOW_PACKLISTS: HounslowPacklist[] = [
  {
    station: 'Recovery Zone',
    lines: [
      { item: 'Marquee - ST 3x3 (or equivalent)', qty: 2 },
      { item: 'Marquee Walls - 3x3 (or equivalent)', qty: 6 },
      { item: 'Esky / Cooler', qty: 2 },
      { item: 'Hammer / Mallet', qty: 1 },
      { item: 'Hose & Fittings / Spray Nozzle', qty: 1 },
      { item: 'Bins - Large Round Black', qty: 2 },
      { item: 'Pegs - Large', qty: 8 },
      { item: 'Ratchet Straps', qty: 8 },
      { item: 'Pegs - Small', qty: 8 },
      { item: 'Trestle Tables', qty: 4 },
      { item: 'Electrical Power Cable (2-3m)', qty: 1 },
      { item: 'Extension Cable (5m+)', qty: 1 },
      { item: 'Power Board', qty: 1 },
      { item: 'Toastie / Jaffle Maker', qty: 1 },
      { item: 'Electric Hot Water Urn', qty: 1 },
      { item: 'Gas Bottle', qty: 1 },
      { item: 'Gas Heater', qty: 1 },
      { item: 'Matches', qty: 1 },
      { item: 'Milo', qty: 1 },
      { item: 'Serving Jugs (2L, marked)', qty: 3 },
      { item: 'Paper Towel / Chux', qty: 2 },
      ...STATION_KIT,
    ],
  },
  {
    station: 'Grand Canyon Carpark',
    lines: [
      { item: 'Marquee - ST 3x3 (or equivalent)', qty: 2 },
      { item: 'Marquee Walls - 3x3 (or equivalent)', qty: 4 },
      { item: 'Chairs - Camping / Folding', qty: 2 },
      { item: 'Weights - Steel 20kg', qty: 8 },
      { item: 'Esky / Cooler', qty: 2 },
      { item: 'Bins - Large Round Black', qty: 2 },
      { item: 'Ratchet Straps', qty: 8 },
      { item: 'Sandbags', qty: 16 },
      { item: 'Tarps', qty: 2 },
      { item: 'Trestle Tables', qty: 4 },
      { item: 'Generator', qty: 1, note: 'Hire 2 generators across the event' },
      SPEAKER,
      { item: 'Serving Jugs (2L, marked)', qty: 3 },
      { item: 'Paper Towel / Chux', qty: 2 },
      { item: 'Toilet Paper', qty: 24, note: 'Public toilet on site' },
      ...STATION_KIT,
    ],
  },
  {
    station: 'Perrys Lookdown',
    lines: [
      { item: 'Marquee - ST 3x3 (or equivalent)', qty: 2 },
      { item: 'Marquee Walls - 3x3 (or equivalent)', qty: 4 },
      { item: 'Chairs - Camping / Folding', qty: 2 },
      { item: 'Chairs - Plastic Bistro', qty: 6 },
      { item: 'Weights - Steel 20kg', qty: 8 },
      { item: 'Esky / Cooler', qty: 3 },
      { item: 'Bins - Large Round Black', qty: 2 },
      { item: 'Ratchet Straps', qty: 8 },
      { item: 'Sandbags', qty: 16 },
      { item: 'Spray Bottle / Backpack (Ice Water)', qty: 1 },
      { item: 'Tarps', qty: 2 },
      { item: 'Trestle Tables', qty: 3 },
      { item: 'Electrical Power Cable (2-3m)', qty: 1 },
      { item: 'Extension Cable (5m+)', qty: 1 },
      { item: 'Generator', qty: 1 },
      { item: 'Jerry Can (Fuel)', qty: 1 },
      { item: 'Power Board', qty: 1 },
      { item: 'Stand Light', qty: 1 },
      { item: 'Starlink', qty: 1 },
      { item: 'Strip Light', qty: 1 },
      { item: 'Wet Weather Electrical Covers', qty: 1 },
      ...HOT_FOOD_KIT,
      SPEAKER,
      { item: 'Serving Jugs (2L, marked)', qty: 4 },
      { item: 'Paper Towel / Chux', qty: 4 },
      { item: 'Toilet Paper', qty: 24 },
      { item: 'IBC Pipe', qty: 1 },
      { item: 'IBC Water Container (1000L)', qty: 1 },
      { item: 'Portable Toilets', qty: 1 },
      ...STATION_KIT,
    ],
  },
  {
    station: 'The Pinnacles Car Park',
    lines: [
      { item: 'Marquee - ST 3x3 (or equivalent)', qty: 3 },
      { item: 'Marquee Walls - 3x3 (or equivalent)', qty: 7 },
      { item: 'Chairs - Camping / Folding', qty: 2 },
      { item: 'Chairs - Plastic Bistro', qty: 6 },
      { item: 'Weights - Steel 20kg', qty: 12 },
      { item: 'Esky / Cooler', qty: 4 },
      { item: 'Hammer / Mallet', qty: 1 },
      { item: 'Bins - Large Round Black', qty: 2 },
      { item: 'Ratchet Straps', qty: 12 },
      { item: 'Sandbags', qty: 20 },
      { item: 'Spray Bottle / Backpack (Ice Water)', qty: 1 },
      { item: 'Tarps', qty: 2 },
      { item: 'Trestle Tables', qty: 4 },
      { item: 'Electrical Power Cable (2-3m)', qty: 1 },
      { item: 'Extension Cable (5m+)', qty: 1 },
      { item: 'Generator', qty: 1 },
      { item: 'Jerry Can (Fuel)', qty: 1 },
      { item: 'Power Board', qty: 1 },
      { item: 'Starlink', qty: 1 },
      { item: 'Wet Weather Electrical Covers', qty: 1 },
      ...HOT_FOOD_KIT,
      SPEAKER,
      { item: 'Serving Jugs (2L, marked)', qty: 4 },
      { item: 'Paper Towel / Chux', qty: 4 },
      { item: 'Toilet Paper', qty: 48 },
      { item: 'IBC Pipe', qty: 2 },
      { item: 'IBC Water Container (1000L)', qty: 2 },
      { item: 'Portable Toilets', qty: 1 },
      ...STATION_KIT,
    ],
  },
  {
    station: 'Allview Escape',
    lines: [
      {
        item: 'Marquee - ST 3x3 (or equivalent)',
        qty: 11,
        note: 'Medical 1 (Lucas brings 1) · bibs 3 · merch 4 · BOH/sound 2 · info 1',
      },
      { item: 'Marquee Walls - 3x3 (or equivalent)', qty: 12 },
      { item: 'Hammer / Mallet', qty: 2 },
      { item: 'Bins - Large Round Black', qty: 2 },
      { item: 'Pegs - Large', qty: 44 },
      { item: 'Ratchet Straps', qty: 44 },
      { item: 'Trestle Tables', qty: 17, note: 'Rego 7 · merch 4 · BOH 4 · spare 2' },
      { item: 'Electrical Power Cable (2-3m)', qty: 14 },
      { item: 'Extension Cable (5m+)', qty: 6 },
      { item: 'Generator', qty: 1 },
      { item: 'Jerry Can (Fuel)', qty: 1 },
      { item: 'Power Board', qty: 6 },
      { item: 'Starlink', qty: 4 },
      { item: 'Strip Light', qty: 10 },
      { item: 'Wet Weather Electrical Covers', qty: 6 },
      { item: 'Coffee (Large Instant)', qty: 5 },
      { item: 'Tea (English Breakfast)', qty: 5 },
      { item: 'Gas Bottle', qty: 2 },
      { item: 'Gas Heater', qty: 2 },
      { item: 'Insulated Hot Cups', qty: 2, note: 'Boxes of 500' },
      { item: 'Matches', qty: 1 },
      { item: 'Cable Ties', qty: 5 },
      SANITISER,
      { item: 'Bin Bags (large / roll)', qty: 4 },
      { item: 'Scissors / Snippers', qty: 5 },
      { item: 'Sunscreen', qty: 10 },
      { item: 'Toilet Paper', qty: 96 },
      { item: 'Coolroom / Coolroom Trailer', qty: 1, note: '1 × Adrian + 1 order' },
      { item: 'Portable Toilets', qty: 10 },
      { item: 'A-Frames (Village Instructions)', qty: 6 },
      { item: 'ASICS Umbrellas', qty: 6 },
      { item: 'ASICS Vehicle', qty: 1 },
      { item: 'Banners / Teardrop Banners / Sponsor Flags', qty: 18, note: 'CCB mesh banners' },
      { item: 'Crowd Barriers', qty: 6, note: 'Sets of 3' },
      { item: 'Extension Cable - 15 AMP', qty: 2 },
      { item: 'Power Electrical Cable (20m+)', qty: 8 },
      { item: 'Festoon Lighting (10m lengths)', qty: 10 },
      { item: 'Inflatable Arch Pump', qty: 2 },
      { item: 'Inflatable Arch', qty: 3, note: '2 × ASICS + 1 × event' },
      { item: 'Inflatable Pillar', qty: 2 },
      { item: 'Lounge Chairs', qty: 8 },
      { item: 'Mesh Banner Toggles', qty: 12 },
      { item: 'PA System / VONYX + Mic + Stand', qty: 1, note: 'Hired from Albury Sound & Lighting' },
      { item: 'Picket Fence', qty: 20 },
      { item: 'Picnic Blankets', qty: 10 },
      { item: 'International / Participant / Presentation Flags', qty: 5, note: 'Pure flags' },
      { item: 'Track Mat / Carpet', qty: 34 },
      { item: 'Umbrella Bases', qty: 6 },
      { item: 'Witches Hats / Cones', qty: 58 },
      { item: 'Internet Dongle', qty: 1 },
      { item: 'Finisher Medals', qty: 1 },
      { item: 'Merchandise', qty: 1 },
      { item: 'Paper (packs)', qty: 2 },
      { item: 'Printer', qty: 1 },
      { item: 'Printer Ink', qty: 1 },
      { item: 'Registration Lists / Distance Signs', qty: 2 },
      { item: 'Safety Pins', qty: 36, note: '3,600 pins — packs of 100' },
      { item: 'Merch - iPad & Square Reader', qty: 2 },
      { item: 'ASICS Marquee (3x3)', qty: 1 },
      { item: 'Merch Racking (complete set)', qty: 1, note: 'Bring everything' },
      { item: 'Plastic Table & Chairs Set', qty: 20 },
      { item: 'Kids Table + Chair Set', qty: 1, note: 'Colin to provide' },
    ],
  },
];

export interface HounslowFoodLine {
  station: string;
  /** Race name from the hc26 entry in eventSeed.ts. */
  race: string;
  /** Food catalogue SKU. */
  sku: string;
  perRunner: number;
  flatQty: number;
}

/*
 * Straight off the sheet, one rule per station per race. Where the marathon
 * passes a station twice with different ratios on each pass, the two are
 * averaged and applied to both passes' runners, which gives the sheet's
 * total exactly. Flat amounts are summed across passes.
 */
export const HOUNSLOW_CONSUMPTION: HounslowFoodLine[] = [
  { station: 'Grand Canyon Carpark', race: 'Marathon', sku: 'FD-01', perRunner: 0.8, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: 'Marathon', sku: 'FD-02', perRunner: 0.02, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: 'Marathon', sku: 'FD-03', perRunner: 0.011236, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: 'Marathon', sku: 'FD-04', perRunner: 0.8, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: 'Marathon', sku: 'FD-05', perRunner: 0.1, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: 'Marathon', sku: 'FD-23', perRunner: 0.1, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: 'Marathon', sku: 'FD-06', perRunner: 0.075, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: 'Marathon', sku: 'FD-07', perRunner: 0.0375, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: 'Marathon', sku: 'FD-08', perRunner: 0.006, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: 'Marathon', sku: 'FD-09', perRunner: 0, flatQty: 1 },
  { station: 'Grand Canyon Carpark', race: 'Marathon', sku: 'FD-10', perRunner: 0, flatQty: 1 },
  { station: 'Grand Canyon Carpark', race: 'Marathon', sku: 'FD-11', perRunner: 0.016667, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: 'Marathon', sku: 'FD-12', perRunner: 0.005, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: 'Marathon', sku: 'FD-13', perRunner: 0.004, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: 'Marathon', sku: 'FD-24', perRunner: 0.05, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: '17k', sku: 'FD-01', perRunner: 1.2, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: '17k', sku: 'FD-02', perRunner: 0.02, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: '17k', sku: 'FD-03', perRunner: 0.011236, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: '17k', sku: 'FD-04', perRunner: 0.8, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: '17k', sku: 'FD-05', perRunner: 0.33, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: '17k', sku: 'FD-23', perRunner: 0.3, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: '17k', sku: 'FD-06', perRunner: 0.15, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: '17k', sku: 'FD-07', perRunner: 0.075, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: '17k', sku: 'FD-08', perRunner: 0.0075, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: '17k', sku: 'FD-11', perRunner: 0.041667, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: '17k', sku: 'FD-12', perRunner: 0.0125, flatQty: 0 },
  { station: 'Grand Canyon Carpark', race: '17k', sku: 'FD-13', perRunner: 0.007, flatQty: 0 },
  { station: 'Allview Escape', race: 'Marathon', sku: 'FD-01', perRunner: 2, flatQty: 0 },
  { station: 'Allview Escape', race: 'Marathon', sku: 'FD-02', perRunner: 0.108, flatQty: 0 },
  { station: 'Allview Escape', race: 'Marathon', sku: 'FD-03', perRunner: 0.012641, flatQty: 0 },
  { station: 'Allview Escape', race: 'Marathon', sku: 'FD-04', perRunner: 0.4, flatQty: 0 },
  { station: 'Allview Escape', race: 'Marathon', sku: 'FD-05', perRunner: 0.415001, flatQty: 0 },
  { station: 'Allview Escape', race: 'Marathon', sku: 'FD-23', perRunner: 0.4, flatQty: 0 },
  { station: 'Allview Escape', race: 'Marathon', sku: 'FD-06', perRunner: 0.175, flatQty: 0 },
  { station: 'Allview Escape', race: 'Marathon', sku: 'FD-07', perRunner: 0.0875, flatQty: 0 },
  { station: 'Allview Escape', race: 'Marathon', sku: 'FD-08', perRunner: 0.0105, flatQty: 0 },
  { station: 'Allview Escape', race: 'Marathon', sku: 'FD-09', perRunner: 0, flatQty: 2 },
  { station: 'Allview Escape', race: 'Marathon', sku: 'FD-10', perRunner: 0, flatQty: 2 },
  { station: 'Allview Escape', race: 'Marathon', sku: 'FD-11', perRunner: 0.048334, flatQty: 0 },
  { station: 'Allview Escape', race: 'Marathon', sku: 'FD-12', perRunner: 0.0145, flatQty: 0 },
  { station: 'Allview Escape', race: 'Marathon', sku: 'FD-13', perRunner: 0.0075, flatQty: 0 },
  { station: 'Allview Escape', race: 'Marathon', sku: 'FD-24', perRunner: 0.05, flatQty: 0 },
  { station: 'Allview Escape', race: '17k', sku: 'FD-01', perRunner: 2, flatQty: 0 },
  { station: 'Allview Escape', race: '17k', sku: 'FD-02', perRunner: 0.04, flatQty: 0 },
  { station: 'Allview Escape', race: '17k', sku: 'FD-03', perRunner: 0.014045, flatQty: 0 },
  { station: 'Allview Escape', race: '17k', sku: 'FD-05', perRunner: 0.5, flatQty: 0 },
  { station: 'Allview Escape', race: '17k', sku: 'FD-23', perRunner: 0.5, flatQty: 0 },
  { station: 'Allview Escape', race: '17k', sku: 'FD-06', perRunner: 0.15, flatQty: 0 },
  { station: 'Allview Escape', race: '17k', sku: 'FD-07', perRunner: 0.075, flatQty: 0 },
  { station: 'Allview Escape', race: '17k', sku: 'FD-08', perRunner: 0.012, flatQty: 0 },
  { station: 'Allview Escape', race: '17k', sku: 'FD-11', perRunner: 0.041667, flatQty: 0 },
  { station: 'Allview Escape', race: '17k', sku: 'FD-12', perRunner: 0.0125, flatQty: 0 },
  { station: 'Allview Escape', race: '17k', sku: 'FD-13', perRunner: 0.007, flatQty: 0 },
  { station: 'Allview Escape', race: 'Kids', sku: 'FD-01', perRunner: 1, flatQty: 0 },
  { station: 'Allview Escape', race: 'Kids', sku: 'FD-02', perRunner: 0.02, flatQty: 0 },
  { station: 'Allview Escape', race: 'Kids', sku: 'FD-03', perRunner: 0.011236, flatQty: 0 },
  { station: 'Allview Escape', race: 'Kids', sku: 'FD-05', perRunner: 0.33, flatQty: 0 },
  { station: 'Allview Escape', race: 'Kids', sku: 'FD-23', perRunner: 0.2, flatQty: 0 },
  { station: 'Allview Escape', race: 'Kids', sku: 'FD-06', perRunner: 0.1, flatQty: 0 },
  { station: 'Allview Escape', race: 'Kids', sku: 'FD-07', perRunner: 0.05, flatQty: 0 },
  { station: 'Allview Escape', race: 'Kids', sku: 'FD-08', perRunner: 0.006, flatQty: 0 },
  { station: 'Allview Escape', race: 'Kids', sku: 'FD-09', perRunner: 0, flatQty: 1 },
  { station: 'Allview Escape', race: 'Kids', sku: 'FD-10', perRunner: 0, flatQty: 1 },
  { station: 'Allview Escape', race: 'Kids', sku: 'FD-11', perRunner: 0.041667, flatQty: 0 },
  { station: 'Allview Escape', race: 'Kids', sku: 'FD-12', perRunner: 0.0125, flatQty: 0 },
  { station: 'Allview Escape', race: 'Kids', sku: 'FD-13', perRunner: 0.007, flatQty: 0 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-01', perRunner: 2.5, flatQty: 0 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-02', perRunner: 0.1, flatQty: 0 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-03', perRunner: 0.011236, flatQty: 0 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-04', perRunner: 0.8, flatQty: 0 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-05', perRunner: 0.33, flatQty: 0 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-23', perRunner: 0.3, flatQty: 0 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-06', perRunner: 0.15, flatQty: 0 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-07', perRunner: 0.075, flatQty: 0 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-08', perRunner: 0.009, flatQty: 0 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-09', perRunner: 0, flatQty: 2 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-10', perRunner: 0, flatQty: 2 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-11', perRunner: 0.041667, flatQty: 0 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-12', perRunner: 0.0125, flatQty: 0 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-13', perRunner: 0.007, flatQty: 0 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-24', perRunner: 0.1325, flatQty: 0 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-14', perRunner: 0.125, flatQty: 0 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-16', perRunner: 0.00625, flatQty: 0 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-17', perRunner: 0, flatQty: 1 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-18', perRunner: 0, flatQty: 1 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-19', perRunner: 0, flatQty: 1 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-20', perRunner: 0, flatQty: 1 },
  { station: 'Perrys Lookdown', race: 'Marathon', sku: 'FD-21', perRunner: 0, flatQty: 1 },
  { station: 'Blue Gum Forest', race: 'Marathon', sku: 'FD-01', perRunner: 0.75, flatQty: 0 },
  { station: 'Blue Gum Forest', race: 'Marathon', sku: 'FD-03', perRunner: 0.011236, flatQty: 0 },
  { station: 'Blue Gum Forest', race: 'Marathon', sku: 'FD-09', perRunner: 0, flatQty: 1 },
  { station: 'Blue Gum Forest', race: 'Marathon', sku: 'FD-10', perRunner: 0, flatQty: 1 },
  { station: 'Blue Gum Forest', race: 'Marathon', sku: 'FD-13', perRunner: 0.007, flatQty: 0 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-01', perRunner: 3, flatQty: 0 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-02', perRunner: 0.15, flatQty: 0 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-03', perRunner: 0.011236, flatQty: 0 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-04', perRunner: 0.8, flatQty: 0 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-05', perRunner: 0.5, flatQty: 0 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-23', perRunner: 0.5, flatQty: 0 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-06', perRunner: 0.2, flatQty: 0 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-07', perRunner: 0.1, flatQty: 0 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-08', perRunner: 0.012, flatQty: 0 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-09', perRunner: 0, flatQty: 1 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-10', perRunner: 0, flatQty: 1 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-11', perRunner: 0.055, flatQty: 0 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-12', perRunner: 0.0165, flatQty: 0 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-13', perRunner: 0.008, flatQty: 0 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-24', perRunner: 0.225, flatQty: 0 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-14', perRunner: 0.5, flatQty: 0 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-16', perRunner: 0.0175, flatQty: 0 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-17', perRunner: 0, flatQty: 1 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-18', perRunner: 0, flatQty: 1 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-19', perRunner: 0, flatQty: 1 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-20', perRunner: 0, flatQty: 1 },
  { station: 'The Pinnacles Car Park', race: 'Marathon', sku: 'FD-21', perRunner: 0, flatQty: 1 },
];
